version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./youtube_analysis.db:/app/youtube_analysis.db
    depends_on:
      - scheduler
    
  scheduler:
    build: .
    command: python scheduler.py
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./youtube_analysis.db:/app/youtube_analysis.db